# fly.toml app configuration file generated for aged-snowflake-9472 on 2023-08-18T03:16:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-snowflake-9472"
primary_region = "arn"

[build]

[env]
  PORT = "3000"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
